apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teesapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/seidutee/minikube-project.git
    targetRevision: main
    path: teesapp

  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
