apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fashion-store-pvc
  namespace: fashionapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
      